version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - app:/app
    depends_on:
      - mysqldb
    networks:
      - spring-app-network

  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    networks:
      - spring-app-network
    volumes:
      - database:/var/lib/mysql

networks:
  spring-app-network:
    driver: bridge

volumes:
  database:
  app:
