version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - app:/app
    depends_on:
      - db
    networks:
      - spring-app-network

  db:
    image: mysql:8.0.28
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    networks:
      - spring-app-network
    volumes:
      - db:/var/lib/mysql

networks:
  spring-app-network:
    driver: bridge

volumes:
  db:
  app:
