version: '3'

services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - jenkis:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    dns:
      - 8.8.8.8

volumes:
  jenkis:
